title: Accounting 101
description: Basic Accounting and Finance for the bored commuter

url: http://accounting101.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: accounting101
  twitter: bananaqpodcast
  facebook: bananaqpodcast
  email: accounting101@abadiez.com
  linkedin: reynanteabadiez

google_analytics: "G-2W9ENQ6M37"

disqus:
  shortname: accounting101
