title: Accounting 101
description: Basic Accounting and Finance for the bored commuter

url: http://accounting101.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github:
  twitter:
  facebook:
  email:
  linkedin:

google_analytics: ""

disqus:
  shortname: accounting101
